[theme]
name = "solarized-dark"
[theme.overrides]
separator = "\u2770"
separator_bg = "#002b36"
separator_fg = "#93a1a1"

[icons]
name = "awesome"

[[block]]
block = "custom"
command = ''' sb-forecast '''
interval = 21600

[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/home/mzeinali/"
alias = ""
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
device = "wls1"
format = "{signal_strength}"
interval = 5

[[block]]
block = "backlight"
device = "/sys/class/backlight/"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "custom"
command = ''' sb-jalalidate '''
interval = "once"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "keyboard_layout"
driver = "sway"
format = " {layout}"
sway_kb_identifier = "1:1:AT_Translated_Set_2_keyboard"
