#!/bin/sh

# Colorize commands when possible.
alias \
    dir='dir --color=auto' \
    vdir='vdir --color=auto' \
    grep='grep --color=auto' \
    egrep='egrep --color=auto' \
    fgrep='fgrep --color=auto' \
    diff='diff --color=auto' \
    ip='ip -color=auto'
    # ls='ls --quoting-style=literal -pq --time-style=iso --color=auto --group-directories-first --show-control-chars'

# Replace "ls" with "exa"
alias \
    ls='exa -ahl --icons --color=always --group-directories-first' \
    la='exa -a --icons --color=always --group-directories-first' \
    ll='exa -l --icons --color=always --group-directories-first' \
    lt='exa -aT --icons --color=always --group-directories-first' \
    lnc='exa --color=never' \
    lsd='lsd -hA --group-dirs first' \
    lst='lsd -A --group-dirs first --tree'

# Replace cat with bat
alias \
    cat='bat' \
    cata='bat -A'

# Replace cd with zoxide
alias cd='z'

# broot
alias \
    bl='br -dp' \
    bs='br -s' \
    br='br -h'

# These common commands are just too long! Abbreviate them.
alias \
    v='nvim' \
    magit='nvim -c MagitOnly' \
    g='git' \
    sdn='sudo shutdown -h now' \
    p='paru' \
    :q='exit'

# Pacman 
alias \
    fixp='sudo rm /var/lib/pacman/db.lck' \
    fixdb='sudo rm /var/lib/pacman/sync/*' \
    cleanup='sudo pacman -Rns `pacman -Qtdq`' \
    listp='pacman -Qqetti | grep -e Name -e Description' \
    mkmirror='curl -s "https://archlinux.org/mirrorlist/?country=IR&country=NL&country=FR&country=DE&protocol=https&use_mirror_status=on" | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -n 7 -'

# Verbosity and settings that you pretty much just always are going to want.
alias \
    cp='cp -iv' \
    mv='mv -iv' \
    rm='rm -vIi' \
    chown='chown -v' \
    chmod='chmod -v' \
    rmdir='rmdir -v' \
    mkd='mkdir -pv' \
    lsblkid='lsblk -o name,label,fstype,size,uuid --noheadings' \
    df='df -h' \
    du='du -ahd 1' \
    ds='dust -d 1' \
    free='free -mh' \
    jctlerror='journalctl -p 3 -xb' \
    dwatch='watch -n 0.1 -t "ls -SsCphq --color=auto --group-directories-first"' \
    yt='youtube-dl --add-metadata -i' \
    yta='yt -x -f bestaudio/best' \
    ffmpeg='ffmpeg -hide_banner' \
    fmpg='ffmpeg -v 0 -stats' \
    ln='ln -v' \
    lynx='lynx -cfg=~/.lynx/lynx.cfg -lss=~/.lynx/lynx.lss -vikeys' \
    a2c='aria2c -c -x 16 -s 16 -k 1M -d' \
    wget='wget -c ' \
    imv='imv -b 1D2330' \
    ts='tabbed surf -pe' \
    ps='ps auxf' \
    psmem='ps auxf | sort -nr -k 4' \
    ipv='ip -br -c a'

# pandoc
alias \
    pdmdpdf='pandoc -t ms --highlight-style=kate -s -o' \
    pdmdhtml='pandoc --highlight-style=kate -s -o' \
    pdmd='pandoc -s -t markdown -o' \
    pddocxmd='pandoc -s --wrap=none --reference-links -t markdown -o'

# scrcpy as webcam
alias scwc="scrcpy --rotation 3 --crop 1080:1400:0:200"

# Using ix.io pastebin
alias pbin="curl -n -F 'f:1=<-' http://ix.io | wl-copy"

# sshd
alias \
    sst="sudo -A systemctl start sshd.service" \
    ssp="sudo -A systemctl stop sshd.service" \
# mpv with input ipc server
alias mpvipc="mpv --input-ipc-server=/tmp/mpvsocket --idle"
